events{}

http{
    upstream user_service{
        server user1:4101;
        server user1:4101;
    }
    upstream order_service{
        server order1:4101;
        server order1:4101;
    }
    server{
        listen 80;
        location /user {
            proxy_pass http://user_service;
        }
        location /order {
            proxy_pass http://order_service;
        }
    }
}